# Generated by Django 3.2.9 on 2021-12-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('category', models.CharField(choices=[('print', 'Принтер'), ('proj', 'Проектор'), ('laptop', 'Ноутбук')], default='print', max_length=10, verbose_name='Категория')),
                ('product_number', models.IntegerField(default=0, verbose_name='Количество товара')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
