# Generated by Django 3.2.9 on 2021-12-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ware', '0003_auto_20211206_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='ordered_product_num',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество занятого товара'),
        ),
    ]
