# Generated by Django 3.2.9 on 2021-12-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ware', '0004_auto_20211206_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ordered_product_num',
            field=models.IntegerField(default=0, verbose_name='Количество занятого товара'),
        ),
    ]
