# Generated by Django 3.2.9 on 2021-12-14 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ware', '0006_auto_20211214_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ebooks',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_ordered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ware.product'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
