# Generated by Django 3.2.9 on 2021-12-14 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ware', '0007_auto_20211214_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ordered_product_num',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='product',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_product_num', models.IntegerField(default=0, verbose_name='Количество занятого товара')),
                ('date_ordered', models.DateTimeField(null=True)),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ware.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ware.profile')),
            ],
        ),
    ]
